[package]
name = "argp_shared"
version = "0.0.0"
authors = ["Jakub Jirutka <jakub@jirutka.cz>"]
edition = "2018"
license = "BSD-3-Clause"
description = "Derive-based argument parsing optimized for code size"
repository = "https://github.com/jirutka/argp"
readme = "README.md"
