name: Release
on:
  release:
    types: [published]

jobs:
  cratesio:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # required for OIDC token exchange
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install asciidoctor and pandoc
        run: sudo apt-get install asciidoctor pandoc

      - name: Convert README to Markdown
        run: |
          printf '# Argp\n\n' > README.md
          asciidoctor -b docbook -o - README.adoc \
              | pandoc -f docbook -t gfm --wrap=preserve --shift-heading-level-by=1 \
              | tee -a argp/README.md argp_derive/README.md

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish to crates.io
        run: |
          cargo publish -p argp_derive --locked --verbose
          cargo publish -p argp --locked --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
